### ISSUE TITLE
How to get body of batch request?

### ISSUE THREAD

**Issue by harelyshau** [cap-js/docs#620]
I need to get body in batch request. What I'm trying to do:
```
cds.app.use((req, res, next) => {
  if (!req.is('multipart/mixed')) return next();
  req.body = '';
  req.on('data', (chunk, ...arg) => {
    req.body += chunk;
  });
  next();
});
```
<img width="500" alt="image" src="https://github.com/cap-js/docs/assets/134649041/da1fcfac-b258-48f8-9b38-2c45c16a7e71">

I get req.body but also get error:
[cds] - DeserializationError: More data required to process multipart
    at ContentDeserializer.readCache (/home/user/projects/ppe-poa/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/okra/odata-server/deserializer/ContentDeserializer.js:156:31)
    at ContentDeserializer._flush (/home/user/projects/ppe-poa/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/okra/odata-server/deserializer/ContentDeserializer.js:109:12)
    at ContentDeserializer.final [as _final] (/home/user/projects/ppe-poa/lib/internal/streams/transform.js:132:10)
    at callFinal (/home/user/projects/ppe-poa/lib/internal/streams/writable.js:698:12)
    at prefinish (/home/user/projects/ppe-poa/lib/internal/streams/writable.js:710:7)
    at finishMaybe (/home/user/projects/ppe-poa/lib/internal/streams/writable.js:720:5)
    at Writable.end (/home/user/projects/ppe-poa/lib/internal/streams/writable.js:634:5)
    at IncomingMessage.onend (/home/user/projects/ppe-poa/lib/internal/streams/readable.js:705:10)
    at Object.onceWrapper (/home/user/projects/ppe-poa/lib/events.js:627:28)
    at IncomingMessage.emit (node:events:513:28) {name: 'DeserializationError', id: '1998244', level: 'WARNING', timestamp: 1704981269502, stack: 'DeserializationError: More data required to p… at IncomingMessage.emit (node:events:513:28)', …}
    
  My question is why I'm getting this error and how to do it without any erros. because it crashes app?
  
  Thanks,
  Pavel.

**Comment by renejeglinsky** [comment]
Hi @harelyshau ,
those kind of questions are better placed in the [community](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce). There a lot of suporting people and also our developers are checking the questions there.
When you have the answer and think this should be documented, I invite you to contribute to capire or reopen this issue and let me know what is missing (probably with a link to the question and answer).
All the best,
René

**Comment by harelyshau** [comment]
Hi @renejeglinsky 
Honestly I'm not sure that community can help with that because I'm using quite standard way to get body from request in expressjs, but some part of SAP CAP kills my app after I'm adding req.on('data', () => {}). And I think the reason of it isn't on my side.

**Comment by renejeglinsky** [comment]
Hi Pavel,
I understand. In that case please use the usual support channels: https://cap.cloud.sap/docs/resources/#reporting-incidents
This repository is only covering documentation contributions, missing information, typos, etc. To get development support, please use the community or report an incident to file a bug. Thank you.

All the best,
René

**Comment by harelyshau** [comment]
@renejeglinsky  got it, thanks. Will create it there
